// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.Data;

#nullable disable

namespace WebShop.Migrations
{
    [DbContext(typeof(BazaDbContext))]
    partial class BazaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebShop.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ime")
                        .HasColumnType("longtext");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prezime")
                        .HasColumnType("longtext");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KorisnikID");

                    b.ToTable("korisnik");
                });

            modelBuilder.Entity("WebShop.Models.Narudzba", b =>
                {
                    b.Property<int>("NarudzbaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumNarudžbe")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<decimal>("UkupnaCijena")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("NarudzbaID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("narudzba");
                });

            modelBuilder.Entity("WebShop.Models.NarudzbaStavka", b =>
                {
                    b.Property<int>("NarudzbaStavkaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NarudzbaID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProizvodID")
                        .HasColumnType("int");

                    b.HasKey("NarudzbaStavkaID");

                    b.HasIndex("NarudzbaID");

                    b.ToTable("narudzba_stavka");
                });

            modelBuilder.Entity("WebShop.Models.Proizvod", b =>
                {
                    b.Property<int>("ProizvodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("proizvodID");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cijena");

                    b.Property<string>("Kategorija")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("kategorija");

                    b.Property<int>("Lager")
                        .HasColumnType("int")
                        .HasColumnName("Lager");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("naziv");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("opis");

                    b.Property<string>("SlikaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slikaUrl");

                    b.HasKey("ProizvodID");

                    b.ToTable("proizvod");
                });

            modelBuilder.Entity("WebShop.Models.Recenzija", b =>
                {
                    b.Property<int>("RecenzijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recenzijaID");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datumKreiranja");

                    b.Property<string>("KorisnikIme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("korisnikIme");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int")
                        .HasColumnName("ocjena");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("tekst");

                    b.HasKey("RecenzijaID");

                    b.ToTable("recenzija");
                });

            modelBuilder.Entity("WebShop.Models.WishList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int")
                        .HasColumnName("korisnikID");

                    b.Property<int>("ProizvodID")
                        .HasColumnType("int")
                        .HasColumnName("proizvodID");

                    b.HasKey("Id");

                    b.HasIndex("ProizvodID");

                    b.ToTable("wishlist");
                });

            modelBuilder.Entity("WebShop.Models.Narudzba", b =>
                {
                    b.HasOne("WebShop.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("WebShop.Models.NarudzbaStavka", b =>
                {
                    b.HasOne("WebShop.Models.Narudzba", "Narudzba")
                        .WithMany("Stavke")
                        .HasForeignKey("NarudzbaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Narudzba");
                });

            modelBuilder.Entity("WebShop.Models.WishList", b =>
                {
                    b.HasOne("WebShop.Models.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("WebShop.Models.Narudzba", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
